#cloud-config

write_files:
  - path: "/home/opc/bootstrap.sh"
    permissions: "0700"
    encoding: "gzip+base64"
    content: |
      ${bootstrap_sh_content}
runcmd:
  - echo "Running configuration script..."
  - sudo bash /home/opc/bootstrap.sh
  #- rm /root/bootstrap.sh

final_message: |
  cloud-init has finished
